#!/usr/bin/env python3

import argparse
import re
from pathlib import Path


SECTION_RE = re.compile(r'^\["(?P<name>(?:\\.|[^"\\])*)"\]$')
ITEM_RE = re.compile(
    r'^"(?P<checkpoint>(?:\\.|[^"\\])*)"\s*=\s*(?P<weight>[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)$'
)


def toml_unquote(value):
    return bytes(value, "utf-8").decode("unicode_escape")


def toml_quote(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Select the largest checkpoint weights from a cluster.toml until "
            "their accumulated weight reaches a threshold."
        )
    )
    parser.add_argument(
        "toml",
        help="Input TOML path. Expected format: [\"benchmark\"] checkpoint = weight.",
    )
    parser.add_argument(
        "threshold",
        type=float,
        help="Accumulated weight threshold, for example 0.9.",
    )
    parser.add_argument(
        "-o",
        "--output",
        default="weight.toml",
        help="Output TOML path.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail on unsupported non-empty lines instead of ignoring them.",
    )
    return parser.parse_args()


def parse_weight_toml(path, strict=False):
    data = {}
    current = None

    with path.open("r", encoding="utf-8") as file:
        for line_no, raw_line in enumerate(file, start=1):
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue

            section = SECTION_RE.match(line)
            if section:
                current = toml_unquote(section.group("name"))
                data.setdefault(current, {})
                continue

            item = ITEM_RE.match(line)
            if item and current is not None:
                checkpoint = toml_unquote(item.group("checkpoint"))
                data[current][checkpoint] = float(item.group("weight"))
                continue

            if strict:
                raise ValueError(f"{path}:{line_no}: unsupported TOML line: {line}")

    return data


def select_by_threshold(items, threshold):
    sorted_items = sorted(
        items.items(),
        key=lambda item: (-item[1], numeric_or_text_key(item[0])),
    )

    selected = []
    total = 0.0
    for checkpoint, weight in sorted_items:
        selected.append((checkpoint, weight))
        total += weight
        if total >= threshold:
            break

    return selected, total


def numeric_or_text_key(value):
    try:
        return (0, int(value))
    except ValueError:
        return (1, value)


def render_toml(selected):
    lines = [
        "# Generated by Deterload/get_weight.py",
        "",
    ]

    for benchmark in sorted(selected):
        items = selected[benchmark]["items"]
        if not items:
            continue

        lines.append(f"[{toml_quote(benchmark)}]")
        lines.append(f"# selected_weight = {selected[benchmark]['total']:.12g}")
        for checkpoint, weight in items:
            lines.append(f"{toml_quote(checkpoint)} = {weight:.12g}")
        lines.append("")

    return "\n".join(lines)


def main():
    args = parse_args()
    if args.threshold <= 0:
        raise ValueError("threshold must be greater than 0")

    input_path = Path(args.toml)
    output_path = Path(args.output)
    data = parse_weight_toml(input_path, strict=args.strict)

    selected = {}
    for benchmark, items in data.items():
        chosen, total = select_by_threshold(items, args.threshold)
        selected[benchmark] = {
            "items": chosen,
            "total": total,
        }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_toml(selected), encoding="utf-8")

    print(f"Wrote {output_path} with {len(selected)} benchmarks")
    for benchmark in sorted(selected):
        count = len(selected[benchmark]["items"])
        total = selected[benchmark]["total"]
        print(f"{benchmark}: {count} checkpoints, selected_weight={total:.12g}")


if __name__ == "__main__":
    main()
